apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment-service
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.236.119
  clusterIPs:
  - 34.118.236.119
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30336
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.198.142.246
      ipMode: VIP